/* eslint-disable max-lines */
import type { OfflineCountry } from './country.types';

export const countries: OfflineCountry[] = [
  {
    countryCode: 'AF',
    countryName: 'Afghanistan',
    flagSrc:
      'https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg',
    phoneCode: '+93',
  },
  {
    countryCode: 'AX',
    countryName: 'Åland Islands',
    flagSrc: 'https://flagcdn.com/ax.svg',
    phoneCode: '+35818',
  },
  {
    countryCode: 'AL',
    countryName: 'Albania',
    flagSrc: 'https://flagcdn.com/al.svg',
    phoneCode: '+355',
  },
  {
    countryCode: 'DZ',
    countryName: 'Algeria',
    flagSrc: 'https://flagcdn.com/dz.svg',
    phoneCode: '+213',
  },
  {
    countryCode: 'AS',
    countryName: 'American Samoa',
    flagSrc: 'https://flagcdn.com/as.svg',
    phoneCode: '+1684',
  },
  {
    countryCode: 'AD',
    countryName: 'Andorra',
    flagSrc: 'https://flagcdn.com/ad.svg',
    phoneCode: '+376',
  },
  {
    countryCode: 'AO',
    countryName: 'Angola',
    flagSrc: 'https://flagcdn.com/ao.svg',
    phoneCode: '+244',
  },
  {
    countryCode: 'AI',
    countryName: 'Anguilla',
    flagSrc: 'https://flagcdn.com/ai.svg',
    phoneCode: '+1264',
  },
  {
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    flagSrc: 'https://flagcdn.com/ag.svg',
    phoneCode: '+1268',
  },
  {
    countryCode: 'AR',
    countryName: 'Argentina',
    flagSrc: 'https://flagcdn.com/ar.svg',
    phoneCode: '+54',
  },
  {
    countryCode: 'AM',
    countryName: 'Armenia',
    flagSrc: 'https://flagcdn.com/am.svg',
    phoneCode: '+374',
  },
  {
    countryCode: 'AW',
    countryName: 'Aruba',
    flagSrc: 'https://flagcdn.com/aw.svg',
    phoneCode: '+297',
  },
  {
    countryCode: 'AU',
    countryName: 'Australia',
    flagSrc: 'https://flagcdn.com/au.svg',
    phoneCode: '+61',
  },
  {
    countryCode: 'AT',
    countryName: 'Austria',
    flagSrc: 'https://flagcdn.com/at.svg',
    phoneCode: '+43',
  },
  {
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    flagSrc: 'https://flagcdn.com/az.svg',
    phoneCode: '+994',
  },
  {
    countryCode: 'BS',
    countryName: 'Bahamas',
    flagSrc: 'https://flagcdn.com/bs.svg',
    phoneCode: '+1242',
  },
  {
    countryCode: 'BH',
    countryName: 'Bahrain',
    flagSrc: 'https://flagcdn.com/bh.svg',
    phoneCode: '+973',
  },
  {
    countryCode: 'BD',
    countryName: 'Bangladesh',
    flagSrc: 'https://flagcdn.com/bd.svg',
    phoneCode: '+880',
  },
  {
    countryCode: 'BB',
    countryName: 'Barbados',
    flagSrc: 'https://flagcdn.com/bb.svg',
    phoneCode: '+1246',
  },
  {
    countryCode: 'BY',
    countryName: 'Belarus',
    flagSrc: 'https://flagcdn.com/by.svg',
    phoneCode: '+375',
  },
  {
    countryCode: 'BE',
    countryName: 'Belgium',
    flagSrc: 'https://flagcdn.com/be.svg',
    phoneCode: '+32',
  },
  {
    countryCode: 'BZ',
    countryName: 'Belize',
    flagSrc: 'https://flagcdn.com/bz.svg',
    phoneCode: '+501',
  },
  {
    countryCode: 'BJ',
    countryName: 'Benin',
    flagSrc: 'https://flagcdn.com/bj.svg',
    phoneCode: '+229',
  },
  {
    countryCode: 'BM',
    countryName: 'Bermuda',
    flagSrc: 'https://flagcdn.com/bm.svg',
    phoneCode: '+1441',
  },
  {
    countryCode: 'BT',
    countryName: 'Bhutan',
    flagSrc: 'https://flagcdn.com/bt.svg',
    phoneCode: '+975',
  },
  {
    countryCode: 'BO',
    countryName: 'Bolivia',
    flagSrc: 'https://flagcdn.com/bo.svg',
    phoneCode: '+591',
  },
  {
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    flagSrc: 'https://flagcdn.com/ba.svg',
    phoneCode: '+387',
  },
  {
    countryCode: 'BW',
    countryName: 'Botswana',
    flagSrc: 'https://flagcdn.com/bw.svg',
    phoneCode: '+267',
  },
  {
    countryCode: 'BV',
    countryName: 'Bouvet Island',
    flagSrc: 'https://flagcdn.com/bv.svg',
    phoneCode: '+47',
  },
  {
    countryCode: 'BR',
    countryName: 'Brazil',
    flagSrc: 'https://flagcdn.com/br.svg',
    phoneCode: '+55',
  },
  {
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    flagSrc: 'https://flagcdn.com/io.svg',
    phoneCode: '+246',
  },
  {
    countryCode: 'VG',
    countryName: 'British Virgin Islands',
    flagSrc: 'https://flagcdn.com/vg.svg',
    phoneCode: '+1284',
  },
  {
    countryCode: 'BN',
    countryName: 'Brunei',
    flagSrc: 'https://flagcdn.com/bn.svg',
    phoneCode: '+673',
  },
  {
    countryCode: 'BG',
    countryName: 'Bulgaria',
    flagSrc: 'https://flagcdn.com/bg.svg',
    phoneCode: '+359',
  },
  {
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    flagSrc: 'https://flagcdn.com/bf.svg',
    phoneCode: '+226',
  },
  {
    countryCode: 'BI',
    countryName: 'Burundi',
    flagSrc: 'https://flagcdn.com/bi.svg',
    phoneCode: '+257',
  },
  {
    countryCode: 'KH',
    countryName: 'Cambodia',
    flagSrc: 'https://flagcdn.com/kh.svg',
    phoneCode: '+855',
  },
  {
    countryCode: 'CM',
    countryName: 'Cameroon',
    flagSrc: 'https://flagcdn.com/cm.svg',
    phoneCode: '+237',
  },
  {
    countryCode: 'CA',
    countryName: 'Canada',
    flagSrc: 'https://flagcdn.com/ca.svg',
    phoneCode: '+1',
  },
  {
    countryCode: 'CV',
    countryName: 'Cape Verde',
    flagSrc: 'https://flagcdn.com/cv.svg',
    phoneCode: '+238',
  },
  {
    countryCode: 'BQ',
    countryName: 'Caribbean Netherlands',
    flagSrc: 'https://flagcdn.com/bq.svg',
    phoneCode: '+599',
  },
  {
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    flagSrc: 'https://flagcdn.com/ky.svg',
    phoneCode: '+1345',
  },
  {
    countryCode: 'CF',
    countryName: 'Central African Republic',
    flagSrc: 'https://flagcdn.com/cf.svg',
    phoneCode: '+236',
  },
  {
    countryCode: 'TD',
    countryName: 'Chad',
    flagSrc: 'https://flagcdn.com/td.svg',
    phoneCode: '+235',
  },
  {
    countryCode: 'CL',
    countryName: 'Chile',
    flagSrc: 'https://flagcdn.com/cl.svg',
    phoneCode: '+56',
  },
  {
    countryCode: 'CN',
    countryName: 'China',
    flagSrc: 'https://flagcdn.com/cn.svg',
    phoneCode: '+86',
  },
  {
    countryCode: 'CX',
    countryName: 'Christmas Island',
    flagSrc: 'https://flagcdn.com/cx.svg',
    phoneCode: '+61',
  },
  {
    countryCode: 'CC',
    countryName: 'Cocos (Keeling) Islands',
    flagSrc: 'https://flagcdn.com/cc.svg',
    phoneCode: '+61',
  },
  {
    countryCode: 'CO',
    countryName: 'Colombia',
    flagSrc: 'https://flagcdn.com/co.svg',
    phoneCode: '+57',
  },
  {
    countryCode: 'KM',
    countryName: 'Comoros',
    flagSrc: 'https://flagcdn.com/km.svg',
    phoneCode: '+269',
  },
  {
    countryCode: 'CK',
    countryName: 'Cook Islands',
    flagSrc: 'https://flagcdn.com/ck.svg',
    phoneCode: '+682',
  },
  {
    countryCode: 'CR',
    countryName: 'Costa Rica',
    flagSrc: 'https://flagcdn.com/cr.svg',
    phoneCode: '+506',
  },
  {
    countryCode: 'HR',
    countryName: 'Croatia',
    flagSrc: 'https://flagcdn.com/hr.svg',
    phoneCode: '+385',
  },
  {
    countryCode: 'CU',
    countryName: 'Cuba',
    flagSrc: 'https://flagcdn.com/cu.svg',
    phoneCode: '+53',
  },
  {
    countryCode: 'CW',
    countryName: 'Curaçao',
    flagSrc: 'https://flagcdn.com/cw.svg',
    phoneCode: '+599',
  },
  {
    countryCode: 'CY',
    countryName: 'Cyprus',
    flagSrc: 'https://flagcdn.com/cy.svg',
    phoneCode: '+357',
  },
  {
    countryCode: 'CZ',
    countryName: 'Czechia',
    flagSrc: 'https://flagcdn.com/cz.svg',
    phoneCode: '+420',
  },
  {
    countryCode: 'DK',
    countryName: 'Denmark',
    flagSrc: 'https://flagcdn.com/dk.svg',
    phoneCode: '+45',
  },
  {
    countryCode: 'DJ',
    countryName: 'Djibouti',
    flagSrc: 'https://flagcdn.com/dj.svg',
    phoneCode: '+253',
  },
  {
    countryCode: 'DM',
    countryName: 'Dominica',
    flagSrc: 'https://flagcdn.com/dm.svg',
    phoneCode: '+1767',
  },
  {
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    flagSrc: 'https://flagcdn.com/do.svg',
    phoneCode: '+1',
  },
  {
    countryCode: 'CD',
    countryName: 'DR Congo',
    flagSrc: 'https://flagcdn.com/cd.svg',
    phoneCode: '+243',
  },
  {
    countryCode: 'EC',
    countryName: 'Ecuador',
    flagSrc: 'https://flagcdn.com/ec.svg',
    phoneCode: '+593',
  },
  {
    countryCode: 'EG',
    countryName: 'Egypt',
    flagSrc: 'https://flagcdn.com/eg.svg',
    phoneCode: '+20',
  },
  {
    countryCode: 'SV',
    countryName: 'El Salvador',
    flagSrc: 'https://flagcdn.com/sv.svg',
    phoneCode: '+503',
  },
  {
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    flagSrc: 'https://flagcdn.com/gq.svg',
    phoneCode: '+240',
  },
  {
    countryCode: 'ER',
    countryName: 'Eritrea',
    flagSrc: 'https://flagcdn.com/er.svg',
    phoneCode: '+291',
  },
  {
    countryCode: 'EE',
    countryName: 'Estonia',
    flagSrc: 'https://flagcdn.com/ee.svg',
    phoneCode: '+372',
  },
  {
    countryCode: 'SZ',
    countryName: 'Eswatini',
    flagSrc: 'https://flagcdn.com/sz.svg',
    phoneCode: '+268',
  },
  {
    countryCode: 'ET',
    countryName: 'Ethiopia',
    flagSrc: 'https://flagcdn.com/et.svg',
    phoneCode: '+251',
  },
  {
    countryCode: 'FK',
    countryName: 'Falkland Islands',
    flagSrc: 'https://flagcdn.com/fk.svg',
    phoneCode: '+500',
  },
  {
    countryCode: 'FO',
    countryName: 'Faroe Islands',
    flagSrc: 'https://flagcdn.com/fo.svg',
    phoneCode: '+298',
  },
  {
    countryCode: 'FJ',
    countryName: 'Fiji',
    flagSrc: 'https://flagcdn.com/fj.svg',
    phoneCode: '+679',
  },
  {
    countryCode: 'FI',
    countryName: 'Finland',
    flagSrc: 'https://flagcdn.com/fi.svg',
    phoneCode: '+358',
  },
  {
    countryCode: 'FR',
    countryName: 'France',
    flagSrc: 'https://flagcdn.com/fr.svg',
    phoneCode: '+33',
  },
  {
    countryCode: 'GF',
    countryName: 'French Guiana',
    flagSrc: 'https://flagcdn.com/gf.svg',
    phoneCode: '+594',
  },
  {
    countryCode: 'PF',
    countryName: 'French Polynesia',
    flagSrc: 'https://flagcdn.com/pf.svg',
    phoneCode: '+689',
  },
  {
    countryCode: 'TF',
    countryName: 'French Southern and Antarctic Lands',
    flagSrc: 'https://flagcdn.com/tf.svg',
    phoneCode: '+262',
  },
  {
    countryCode: 'GA',
    countryName: 'Gabon',
    flagSrc: 'https://flagcdn.com/ga.svg',
    phoneCode: '+241',
  },
  {
    countryCode: 'GM',
    countryName: 'Gambia',
    flagSrc: 'https://flagcdn.com/gm.svg',
    phoneCode: '+220',
  },
  {
    countryCode: 'GE',
    countryName: 'Georgia',
    flagSrc: 'https://flagcdn.com/ge.svg',
    phoneCode: '+995',
  },
  {
    countryCode: 'DE',
    countryName: 'Germany',
    flagSrc: 'https://flagcdn.com/de.svg',
    phoneCode: '+49',
  },
  {
    countryCode: 'GH',
    countryName: 'Ghana',
    flagSrc: 'https://flagcdn.com/gh.svg',
    phoneCode: '+233',
  },
  {
    countryCode: 'GI',
    countryName: 'Gibraltar',
    flagSrc: 'https://flagcdn.com/gi.svg',
    phoneCode: '+350',
  },
  {
    countryCode: 'GR',
    countryName: 'Greece',
    flagSrc: 'https://flagcdn.com/gr.svg',
    phoneCode: '+30',
  },
  {
    countryCode: 'GL',
    countryName: 'Greenland',
    flagSrc: 'https://flagcdn.com/gl.svg',
    phoneCode: '+299',
  },
  {
    countryCode: 'GD',
    countryName: 'Grenada',
    flagSrc: 'https://flagcdn.com/gd.svg',
    phoneCode: '+1473',
  },
  {
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    flagSrc: 'https://flagcdn.com/gp.svg',
    phoneCode: '+590',
  },
  {
    countryCode: 'GU',
    countryName: 'Guam',
    flagSrc: 'https://flagcdn.com/gu.svg',
    phoneCode: '+1671',
  },
  {
    countryCode: 'GT',
    countryName: 'Guatemala',
    flagSrc: 'https://flagcdn.com/gt.svg',
    phoneCode: '+502',
  },
  {
    countryCode: 'GG',
    countryName: 'Guernsey',
    flagSrc: 'https://flagcdn.com/gg.svg',
    phoneCode: '+44',
  },
  {
    countryCode: 'GN',
    countryName: 'Guinea',
    flagSrc: 'https://flagcdn.com/gn.svg',
    phoneCode: '+224',
  },
  {
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    flagSrc: 'https://flagcdn.com/gw.svg',
    phoneCode: '+245',
  },
  {
    countryCode: 'GY',
    countryName: 'Guyana',
    flagSrc: 'https://flagcdn.com/gy.svg',
    phoneCode: '+592',
  },
  {
    countryCode: 'HT',
    countryName: 'Haiti',
    flagSrc: 'https://flagcdn.com/ht.svg',
    phoneCode: '+509',
  },
  {
    countryCode: 'HN',
    countryName: 'Honduras',
    flagSrc: 'https://flagcdn.com/hn.svg',
    phoneCode: '+504',
  },
  {
    countryCode: 'HK',
    countryName: 'Hong Kong',
    flagSrc: 'https://flagcdn.com/hk.svg',
    phoneCode: '+852',
  },
  {
    countryCode: 'HU',
    countryName: 'Hungary',
    flagSrc: 'https://flagcdn.com/hu.svg',
    phoneCode: '+36',
  },
  {
    countryCode: 'IS',
    countryName: 'Iceland',
    flagSrc: 'https://flagcdn.com/is.svg',
    phoneCode: '+354',
  },
  {
    countryCode: 'IN',
    countryName: 'India',
    flagSrc: 'https://flagcdn.com/in.svg',
    phoneCode: '+91',
  },
  {
    countryCode: 'ID',
    countryName: 'Indonesia',
    flagSrc: 'https://flagcdn.com/id.svg',
    phoneCode: '+62',
  },
  {
    countryCode: 'IR',
    countryName: 'Iran',
    flagSrc: 'https://flagcdn.com/ir.svg',
    phoneCode: '+98',
  },
  {
    countryCode: 'IQ',
    countryName: 'Iraq',
    flagSrc: 'https://flagcdn.com/iq.svg',
    phoneCode: '+964',
  },
  {
    countryCode: 'IE',
    countryName: 'Ireland',
    flagSrc: 'https://flagcdn.com/ie.svg',
    phoneCode: '+353',
  },
  {
    countryCode: 'IM',
    countryName: 'Isle of Man',
    flagSrc: 'https://flagcdn.com/im.svg',
    phoneCode: '+44',
  },
  {
    countryCode: 'IL',
    countryName: 'Israel',
    flagSrc: 'https://flagcdn.com/il.svg',
    phoneCode: '+972',
  },
  {
    countryCode: 'IT',
    countryName: 'Italy',
    flagSrc: 'https://flagcdn.com/it.svg',
    phoneCode: '+39',
  },
  {
    countryCode: 'CI',
    countryName: 'Ivory Coast',
    flagSrc: 'https://flagcdn.com/ci.svg',
    phoneCode: '+225',
  },
  {
    countryCode: 'JM',
    countryName: 'Jamaica',
    flagSrc: 'https://flagcdn.com/jm.svg',
    phoneCode: '+1876',
  },
  {
    countryCode: 'JP',
    countryName: 'Japan',
    flagSrc: 'https://flagcdn.com/jp.svg',
    phoneCode: '+81',
  },
  {
    countryCode: 'JE',
    countryName: 'Jersey',
    flagSrc: 'https://flagcdn.com/je.svg',
    phoneCode: '+44',
  },
  {
    countryCode: 'JO',
    countryName: 'Jordan',
    flagSrc: 'https://flagcdn.com/jo.svg',
    phoneCode: '+962',
  },
  {
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    flagSrc: 'https://flagcdn.com/kz.svg',
    phoneCode: '+7',
  },
  {
    countryCode: 'KE',
    countryName: 'Kenya',
    flagSrc: 'https://flagcdn.com/ke.svg',
    phoneCode: '+254',
  },
  {
    countryCode: 'KI',
    countryName: 'Kiribati',
    flagSrc: 'https://flagcdn.com/ki.svg',
    phoneCode: '+686',
  },
  {
    countryCode: 'XK',
    countryName: 'Kosovo',
    flagSrc: 'https://flagcdn.com/xk.svg',
    phoneCode: '+383',
  },
  {
    countryCode: 'KW',
    countryName: 'Kuwait',
    flagSrc: 'https://flagcdn.com/kw.svg',
    phoneCode: '+965',
  },
  {
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    flagSrc: 'https://flagcdn.com/kg.svg',
    phoneCode: '+996',
  },
  {
    countryCode: 'LA',
    countryName: 'Laos',
    flagSrc: 'https://flagcdn.com/la.svg',
    phoneCode: '+856',
  },
  {
    countryCode: 'LV',
    countryName: 'Latvia',
    flagSrc: 'https://flagcdn.com/lv.svg',
    phoneCode: '+371',
  },
  {
    countryCode: 'LB',
    countryName: 'Lebanon',
    flagSrc: 'https://flagcdn.com/lb.svg',
    phoneCode: '+961',
  },
  {
    countryCode: 'LS',
    countryName: 'Lesotho',
    flagSrc: 'https://flagcdn.com/ls.svg',
    phoneCode: '+266',
  },
  {
    countryCode: 'LR',
    countryName: 'Liberia',
    flagSrc: 'https://flagcdn.com/lr.svg',
    phoneCode: '+231',
  },
  {
    countryCode: 'LY',
    countryName: 'Libya',
    flagSrc: 'https://flagcdn.com/ly.svg',
    phoneCode: '+218',
  },
  {
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    flagSrc: 'https://flagcdn.com/li.svg',
    phoneCode: '+423',
  },
  {
    countryCode: 'LT',
    countryName: 'Lithuania',
    flagSrc: 'https://flagcdn.com/lt.svg',
    phoneCode: '+370',
  },
  {
    countryCode: 'LU',
    countryName: 'Luxembourg',
    flagSrc: 'https://flagcdn.com/lu.svg',
    phoneCode: '+352',
  },
  {
    countryCode: 'MO',
    countryName: 'Macau',
    flagSrc: 'https://flagcdn.com/mo.svg',
    phoneCode: '+853',
  },
  {
    countryCode: 'MG',
    countryName: 'Madagascar',
    flagSrc: 'https://flagcdn.com/mg.svg',
    phoneCode: '+261',
  },
  {
    countryCode: 'MW',
    countryName: 'Malawi',
    flagSrc: 'https://flagcdn.com/mw.svg',
    phoneCode: '+265',
  },
  {
    countryCode: 'MY',
    countryName: 'Malaysia',
    flagSrc: 'https://flagcdn.com/my.svg',
    phoneCode: '+60',
  },
  {
    countryCode: 'MV',
    countryName: 'Maldives',
    flagSrc: 'https://flagcdn.com/mv.svg',
    phoneCode: '+960',
  },
  {
    countryCode: 'ML',
    countryName: 'Mali',
    flagSrc: 'https://flagcdn.com/ml.svg',
    phoneCode: '+223',
  },
  {
    countryCode: 'MT',
    countryName: 'Malta',
    flagSrc: 'https://flagcdn.com/mt.svg',
    phoneCode: '+356',
  },
  {
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    flagSrc: 'https://flagcdn.com/mh.svg',
    phoneCode: '+692',
  },
  {
    countryCode: 'MQ',
    countryName: 'Martinique',
    flagSrc: 'https://flagcdn.com/mq.svg',
    phoneCode: '+596',
  },
  {
    countryCode: 'MR',
    countryName: 'Mauritania',
    flagSrc: 'https://flagcdn.com/mr.svg',
    phoneCode: '+222',
  },
  {
    countryCode: 'MU',
    countryName: 'Mauritius',
    flagSrc: 'https://flagcdn.com/mu.svg',
    phoneCode: '+230',
  },
  {
    countryCode: 'YT',
    countryName: 'Mayotte',
    flagSrc: 'https://flagcdn.com/yt.svg',
    phoneCode: '+262',
  },
  {
    countryCode: 'MX',
    countryName: 'Mexico',
    flagSrc: 'https://flagcdn.com/mx.svg',
    phoneCode: '+52',
  },
  {
    countryCode: 'FM',
    countryName: 'Micronesia',
    flagSrc: 'https://flagcdn.com/fm.svg',
    phoneCode: '+691',
  },
  {
    countryCode: 'MD',
    countryName: 'Moldova',
    flagSrc: 'https://flagcdn.com/md.svg',
    phoneCode: '+373',
  },
  {
    countryCode: 'MC',
    countryName: 'Monaco',
    flagSrc: 'https://flagcdn.com/mc.svg',
    phoneCode: '+377',
  },
  {
    countryCode: 'MN',
    countryName: 'Mongolia',
    flagSrc: 'https://flagcdn.com/mn.svg',
    phoneCode: '+976',
  },
  {
    countryCode: 'ME',
    countryName: 'Montenegro',
    flagSrc: 'https://flagcdn.com/me.svg',
    phoneCode: '+382',
  },
  {
    countryCode: 'MS',
    countryName: 'Montserrat',
    flagSrc: 'https://flagcdn.com/ms.svg',
    phoneCode: '+1664',
  },
  {
    countryCode: 'MA',
    countryName: 'Morocco',
    flagSrc: 'https://flagcdn.com/ma.svg',
    phoneCode: '+212',
  },
  {
    countryCode: 'MZ',
    countryName: 'Mozambique',
    flagSrc: 'https://flagcdn.com/mz.svg',
    phoneCode: '+258',
  },
  {
    countryCode: 'MM',
    countryName: 'Myanmar',
    flagSrc: 'https://flagcdn.com/mm.svg',
    phoneCode: '+95',
  },
  {
    countryCode: 'NA',
    countryName: 'Namibia',
    flagSrc: 'https://flagcdn.com/na.svg',
    phoneCode: '+264',
  },
  {
    countryCode: 'NR',
    countryName: 'Nauru',
    flagSrc: 'https://flagcdn.com/nr.svg',
    phoneCode: '+674',
  },
  {
    countryCode: 'NP',
    countryName: 'Nepal',
    flagSrc: 'https://flagcdn.com/np.svg',
    phoneCode: '+977',
  },
  {
    countryCode: 'NL',
    countryName: 'Netherlands',
    flagSrc: 'https://flagcdn.com/nl.svg',
    phoneCode: '+31',
  },
  {
    countryCode: 'NC',
    countryName: 'New Caledonia',
    flagSrc: 'https://flagcdn.com/nc.svg',
    phoneCode: '+687',
  },
  {
    countryCode: 'NZ',
    countryName: 'New Zealand',
    flagSrc: 'https://flagcdn.com/nz.svg',
    phoneCode: '+64',
  },
  {
    countryCode: 'NI',
    countryName: 'Nicaragua',
    flagSrc: 'https://flagcdn.com/ni.svg',
    phoneCode: '+505',
  },
  {
    countryCode: 'NE',
    countryName: 'Niger',
    flagSrc: 'https://flagcdn.com/ne.svg',
    phoneCode: '+227',
  },
  {
    countryCode: 'NG',
    countryName: 'Nigeria',
    flagSrc: 'https://flagcdn.com/ng.svg',
    phoneCode: '+234',
  },
  {
    countryCode: 'NU',
    countryName: 'Niue',
    flagSrc: 'https://flagcdn.com/nu.svg',
    phoneCode: '+683',
  },
  {
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    flagSrc: 'https://flagcdn.com/nf.svg',
    phoneCode: '+672',
  },
  {
    countryCode: 'KP',
    countryName: 'North Korea',
    flagSrc: 'https://flagcdn.com/kp.svg',
    phoneCode: '+850',
  },
  {
    countryCode: 'MK',
    countryName: 'North Macedonia',
    flagSrc: 'https://flagcdn.com/mk.svg',
    phoneCode: '+389',
  },
  {
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    flagSrc: 'https://flagcdn.com/mp.svg',
    phoneCode: '+1670',
  },
  {
    countryCode: 'NO',
    countryName: 'Norway',
    flagSrc: 'https://flagcdn.com/no.svg',
    phoneCode: '+47',
  },
  {
    countryCode: 'OM',
    countryName: 'Oman',
    flagSrc: 'https://flagcdn.com/om.svg',
    phoneCode: '+968',
  },
  {
    countryCode: 'PK',
    countryName: 'Pakistan',
    flagSrc: 'https://flagcdn.com/pk.svg',
    phoneCode: '+92',
  },
  {
    countryCode: 'PW',
    countryName: 'Palau',
    flagSrc: 'https://flagcdn.com/pw.svg',
    phoneCode: '+680',
  },
  {
    countryCode: 'PS',
    countryName: 'Palestine',
    flagSrc: 'https://flagcdn.com/ps.svg',
    phoneCode: '+970',
  },
  {
    countryCode: 'PA',
    countryName: 'Panama',
    flagSrc: 'https://flagcdn.com/pa.svg',
    phoneCode: '+507',
  },
  {
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    flagSrc: 'https://flagcdn.com/pg.svg',
    phoneCode: '+675',
  },
  {
    countryCode: 'PY',
    countryName: 'Paraguay',
    flagSrc: 'https://flagcdn.com/py.svg',
    phoneCode: '+595',
  },
  {
    countryCode: 'PE',
    countryName: 'Peru',
    flagSrc: 'https://flagcdn.com/pe.svg',
    phoneCode: '+51',
  },
  {
    countryCode: 'PH',
    countryName: 'Philippines',
    flagSrc: 'https://flagcdn.com/ph.svg',
    phoneCode: '+63',
  },
  {
    countryCode: 'PN',
    countryName: 'Pitcairn Islands',
    flagSrc: 'https://flagcdn.com/pn.svg',
    phoneCode: '+64',
  },
  {
    countryCode: 'PL',
    countryName: 'Poland',
    flagSrc: 'https://flagcdn.com/pl.svg',
    phoneCode: '+48',
  },
  {
    countryCode: 'PT',
    countryName: 'Portugal',
    flagSrc: 'https://flagcdn.com/pt.svg',
    phoneCode: '+351',
  },
  {
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    flagSrc: 'https://flagcdn.com/pr.svg',
    phoneCode: '+1',
  },
  {
    countryCode: 'QA',
    countryName: 'Qatar',
    flagSrc: 'https://flagcdn.com/qa.svg',
    phoneCode: '+974',
  },
  {
    countryCode: 'CG',
    countryName: 'Republic of the Congo',
    flagSrc: 'https://flagcdn.com/cg.svg',
    phoneCode: '+242',
  },
  {
    countryCode: 'RE',
    countryName: 'Réunion',
    flagSrc: 'https://flagcdn.com/re.svg',
    phoneCode: '+262',
  },
  {
    countryCode: 'RO',
    countryName: 'Romania',
    flagSrc: 'https://flagcdn.com/ro.svg',
    phoneCode: '+40',
  },
  {
    countryCode: 'RU',
    countryName: 'Russia',
    flagSrc: 'https://flagcdn.com/ru.svg',
    phoneCode: '+7',
  },
  {
    countryCode: 'RW',
    countryName: 'Rwanda',
    flagSrc: 'https://flagcdn.com/rw.svg',
    phoneCode: '+250',
  },
  {
    countryCode: 'BL',
    countryName: 'Saint Barthélemy',
    flagSrc: 'https://flagcdn.com/bl.svg',
    phoneCode: '+590',
  },
  {
    countryCode: 'SH',
    countryName: 'Saint Helena, Ascension and Tristan da Cunha',
    flagSrc: 'https://flagcdn.com/sh.svg',
    phoneCode: '+2',
  },
  {
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    flagSrc: 'https://flagcdn.com/kn.svg',
    phoneCode: '+1869',
  },
  {
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    flagSrc: 'https://flagcdn.com/lc.svg',
    phoneCode: '+1758',
  },
  {
    countryCode: 'MF',
    countryName: 'Saint Martin',
    flagSrc: 'https://flagcdn.com/mf.svg',
    phoneCode: '+590',
  },
  {
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    flagSrc: 'https://flagcdn.com/pm.svg',
    phoneCode: '+508',
  },
  {
    countryCode: 'VC',
    countryName: 'Saint Vincent and the Grenadines',
    flagSrc: 'https://flagcdn.com/vc.svg',
    phoneCode: '+1784',
  },
  {
    countryCode: 'WS',
    countryName: 'Samoa',
    flagSrc: 'https://flagcdn.com/ws.svg',
    phoneCode: '+685',
  },
  {
    countryCode: 'SM',
    countryName: 'San Marino',
    flagSrc: 'https://flagcdn.com/sm.svg',
    phoneCode: '+378',
  },
  {
    countryCode: 'ST',
    countryName: 'São Tomé and Príncipe',
    flagSrc: 'https://flagcdn.com/st.svg',
    phoneCode: '+239',
  },
  {
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    flagSrc: 'https://flagcdn.com/sa.svg',
    phoneCode: '+966',
  },
  {
    countryCode: 'SN',
    countryName: 'Senegal',
    flagSrc: 'https://flagcdn.com/sn.svg',
    phoneCode: '+221',
  },
  {
    countryCode: 'RS',
    countryName: 'Serbia',
    flagSrc: 'https://flagcdn.com/rs.svg',
    phoneCode: '+381',
  },
  {
    countryCode: 'SC',
    countryName: 'Seychelles',
    flagSrc: 'https://flagcdn.com/sc.svg',
    phoneCode: '+248',
  },
  {
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    flagSrc: 'https://flagcdn.com/sl.svg',
    phoneCode: '+232',
  },
  {
    countryCode: 'SG',
    countryName: 'Singapore',
    flagSrc: 'https://flagcdn.com/sg.svg',
    phoneCode: '+65',
  },
  {
    countryCode: 'SX',
    countryName: 'Sint Maarten',
    flagSrc: 'https://flagcdn.com/sx.svg',
    phoneCode: '+1721',
  },
  {
    countryCode: 'SK',
    countryName: 'Slovakia',
    flagSrc: 'https://flagcdn.com/sk.svg',
    phoneCode: '+421',
  },
  {
    countryCode: 'SI',
    countryName: 'Slovenia',
    flagSrc: 'https://flagcdn.com/si.svg',
    phoneCode: '+386',
  },
  {
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    flagSrc: 'https://flagcdn.com/sb.svg',
    phoneCode: '+677',
  },
  {
    countryCode: 'SO',
    countryName: 'Somalia',
    flagSrc: 'https://flagcdn.com/so.svg',
    phoneCode: '+252',
  },
  {
    countryCode: 'ZA',
    countryName: 'South Africa',
    flagSrc: 'https://flagcdn.com/za.svg',
    phoneCode: '+27',
  },
  {
    countryCode: 'GS',
    countryName: 'South Georgia',
    flagSrc: 'https://flagcdn.com/gs.svg',
    phoneCode: '+500',
  },
  {
    countryCode: 'KR',
    countryName: 'South Korea',
    flagSrc: 'https://flagcdn.com/kr.svg',
    phoneCode: '+82',
  },
  {
    countryCode: 'SS',
    countryName: 'South Sudan',
    flagSrc: 'https://flagcdn.com/ss.svg',
    phoneCode: '+211',
  },
  {
    countryCode: 'ES',
    countryName: 'Spain',
    flagSrc: 'https://flagcdn.com/es.svg',
    phoneCode: '+34',
  },
  {
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    flagSrc: 'https://flagcdn.com/lk.svg',
    phoneCode: '+94',
  },
  {
    countryCode: 'SD',
    countryName: 'Sudan',
    flagSrc: 'https://flagcdn.com/sd.svg',
    phoneCode: '+249',
  },
  {
    countryCode: 'SR',
    countryName: 'Suriname',
    flagSrc: 'https://flagcdn.com/sr.svg',
    phoneCode: '+597',
  },
  {
    countryCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    flagSrc: 'https://flagcdn.com/sj.svg',
    phoneCode: '+4779',
  },
  {
    countryCode: 'SE',
    countryName: 'Sweden',
    flagSrc: 'https://flagcdn.com/se.svg',
    phoneCode: '+46',
  },
  {
    countryCode: 'CH',
    countryName: 'Switzerland',
    flagSrc: 'https://flagcdn.com/ch.svg',
    phoneCode: '+41',
  },
  {
    countryCode: 'SY',
    countryName: 'Syria',
    flagSrc: 'https://flagcdn.com/sy.svg',
    phoneCode: '+963',
  },
  {
    countryCode: 'TW',
    countryName: 'Taiwan',
    flagSrc: 'https://flagcdn.com/tw.svg',
    phoneCode: '+886',
  },
  {
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    flagSrc: 'https://flagcdn.com/tj.svg',
    phoneCode: '+992',
  },
  {
    countryCode: 'TZ',
    countryName: 'Tanzania',
    flagSrc: 'https://flagcdn.com/tz.svg',
    phoneCode: '+255',
  },
  {
    countryCode: 'TH',
    countryName: 'Thailand',
    flagSrc: 'https://flagcdn.com/th.svg',
    phoneCode: '+66',
  },
  {
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    flagSrc: 'https://flagcdn.com/tl.svg',
    phoneCode: '+670',
  },
  {
    countryCode: 'TG',
    countryName: 'Togo',
    flagSrc: 'https://flagcdn.com/tg.svg',
    phoneCode: '+228',
  },
  {
    countryCode: 'TK',
    countryName: 'Tokelau',
    flagSrc: 'https://flagcdn.com/tk.svg',
    phoneCode: '+690',
  },
  {
    countryCode: 'TO',
    countryName: 'Tonga',
    flagSrc: 'https://flagcdn.com/to.svg',
    phoneCode: '+676',
  },
  {
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    flagSrc: 'https://flagcdn.com/tt.svg',
    phoneCode: '+1868',
  },
  {
    countryCode: 'TN',
    countryName: 'Tunisia',
    flagSrc: 'https://flagcdn.com/tn.svg',
    phoneCode: '+216',
  },
  {
    countryCode: 'TR',
    countryName: 'Turkey',
    flagSrc: 'https://flagcdn.com/tr.svg',
    phoneCode: '+90',
  },
  {
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    flagSrc: 'https://flagcdn.com/tm.svg',
    phoneCode: '+993',
  },
  {
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    flagSrc: 'https://flagcdn.com/tc.svg',
    phoneCode: '+1649',
  },
  {
    countryCode: 'TV',
    countryName: 'Tuvalu',
    flagSrc: 'https://flagcdn.com/tv.svg',
    phoneCode: '+688',
  },
  {
    countryCode: 'UG',
    countryName: 'Uganda',
    flagSrc: 'https://flagcdn.com/ug.svg',
    phoneCode: '+256',
  },
  {
    countryCode: 'UA',
    countryName: 'Ukraine',
    flagSrc: 'https://flagcdn.com/ua.svg',
    phoneCode: '+380',
  },
  {
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    flagSrc: 'https://flagcdn.com/ae.svg',
    phoneCode: '+971',
  },
  {
    countryCode: 'GB',
    countryName: 'United Kingdom',
    flagSrc: 'https://flagcdn.com/gb.svg',
    phoneCode: '+44',
  },
  {
    countryCode: 'US',
    countryName: 'United States',
    flagSrc: 'https://flagcdn.com/us.svg',
    phoneCode: '+1',
  },
  {
    countryCode: 'UM',
    countryName: 'United States Minor Outlying Islands',
    flagSrc: 'https://flagcdn.com/um.svg',
    phoneCode: '+268',
  },
  {
    countryCode: 'VI',
    countryName: 'United States Virgin Islands',
    flagSrc: 'https://flagcdn.com/vi.svg',
    phoneCode: '+1340',
  },
  {
    countryCode: 'UY',
    countryName: 'Uruguay',
    flagSrc: 'https://flagcdn.com/uy.svg',
    phoneCode: '+598',
  },
  {
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    flagSrc: 'https://flagcdn.com/uz.svg',
    phoneCode: '+998',
  },
  {
    countryCode: 'VU',
    countryName: 'Vanuatu',
    flagSrc: 'https://flagcdn.com/vu.svg',
    phoneCode: '+678',
  },
  {
    countryCode: 'VA',
    countryName: 'Vatican City',
    flagSrc: 'https://flagcdn.com/va.svg',
    phoneCode: '+3',
  },
  {
    countryCode: 'VE',
    countryName: 'Venezuela',
    flagSrc: 'https://flagcdn.com/ve.svg',
    phoneCode: '+58',
  },
  {
    countryCode: 'VN',
    countryName: 'Vietnam',
    flagSrc: 'https://flagcdn.com/vn.svg',
    phoneCode: '+84',
  },
  {
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    flagSrc: 'https://flagcdn.com/wf.svg',
    phoneCode: '+681',
  },
  {
    countryCode: 'EH',
    countryName: 'Western Sahara',
    flagSrc: 'https://flagcdn.com/eh.svg',
    phoneCode: '+2',
  },
  {
    countryCode: 'YE',
    countryName: 'Yemen',
    flagSrc: 'https://flagcdn.com/ye.svg',
    phoneCode: '+967',
  },
  {
    countryCode: 'ZM',
    countryName: 'Zambia',
    flagSrc: 'https://flagcdn.com/zm.svg',
    phoneCode: '+260',
  },
  {
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    flagSrc: 'https://flagcdn.com/zw.svg',
    phoneCode: '+263',
  },
];
